pabi2/pb2_generic

- account_budget_activity/models/account.py
- account_budget_activity/models/account_budget.py
> [FIX] account_budget_activity, change constant BUDGETING_LEVEL move to

- account_invoice_cancel_reason/__init__.py
- account_invoice_cancel_reason/__openerp__.py
- account_invoice_cancel_reason/model/__init__.py
- account_invoice_cancel_reason/model/account_invoice.py
- account_invoice_cancel_reason/security/ir.model.access.csv
- account_invoice_cancel_reason/view/account_invoice_view.xml
- account_invoice_cancel_reason/wizard/__init__.py
- account_invoice_cancel_reason/wizard/cancel_reason.py
- account_invoice_cancel_reason/wizard/cancel_reason_view.xml
- purchase_invoice_plan/wizard/purchase_create_invoice_plan.py
And small fix in purchase_invoice_plan
> [ADD] account_invoice_cancel_reason

- account_move_line_doc_ref/__init__.py
- account_move_line_doc_ref/__openerp__.py
- account_move_line_doc_ref/models/__init__.py
- account_move_line_doc_ref/models/account_invoice.py
- account_move_line_doc_ref/models/account_move_line.py
- account_move_line_doc_ref/views/account_move_line_view.xml
- account_voucher_deduction/models/account_voucher.py
- stock_move_line_doc_ref/__init__.py
- stock_move_line_doc_ref/__openerp__.py
- stock_move_line_doc_ref/models/__init__.py
- stock_move_line_doc_ref/models/stock.py
- voucher_move_line_doc_ref/__init__.py
- voucher_move_line_doc_ref/__openerp__.py
- voucher_move_line_doc_ref/models/__init__.py
- voucher_move_line_doc_ref/models/account_voucher.py
- voucher_move_line_doc_ref/views/account_voucher_view.xml
Hi Kitti,
This addon, will add new "doc_ref" field in account.move.line, and filled when,
Invoices (customer/supplier and including refunds, etc.)
Payment (customer/supplier)
Expense (don't need anymore as we use hr_expense_auto_invoice)
etc., anything else as you see when coding.
Thanks,
> Add account move line doc ref

- purchase_split_quote2order/views/purchase_view.xml
Please merge this to master krub. It just sets PO 'Approve' button visibility.
> [FIX] set visibility to Approve Button

- l10n_th_vat_report/__init__.py
- l10n_th_vat_report/__openerp__.py
- l10n_th_vat_report/report/__init__.py
- l10n_th_vat_report/report/vat_report.py
- l10n_th_vat_report/views/report.xml
- l10n_th_vat_report/views/report_view.xml
- l10n_th_vat_report/wizard/__init__.py
- l10n_th_vat_report/wizard/vat_report_wizard.py
- l10n_th_vat_report/wizard/vat_report_wizard_view.xml
Hi Kitti,
Improved with invoice tax object consideration.
Thanks,
> [ADD]l10n_th_vat_report: added new module

- l10n_th_vat_report/views/report_view.xml
Hi Kitti,
Layout improve for thai report. Issue 396
Thanks
> [IMP]l10n_th_vat_report: made report font smaller

- purchase_split_quote2order/models/purchase.py
- res_partner_ext/__openerp__.py
- res_partner_ext/partner.py
- res_partner_ext/partner_view.xml
- res_partner_ext/security/ir.model.access.csv
Please have a quick review. If it's OK, please merge this to master krub.
> Enh siraparn res partner ext

- res_partner_ext/__openerp__.py
- res_partner_ext/partner.py
- res_partner_ext/partner_view.xml
[FIX] inherit vat and taxbranch from l10n_th_fields and take out duplicate fields in view
> [FIX] inherit vat and taxbranch from l10n_th_fields

- res_partner_ext/partner_view.xml
please merge this to master krub
> [ENH] Add partner tag management menu

- account_cancel_with_reversal/models/account_invoice.py
- account_cancel_with_reversal/models/account_voucher.py
- account_cancel_with_reversal/views/account_invoice_view.xml
- account_cancel_with_reversal/views/account_voucher_view.xml
- account_cancel_with_reversal/wizard/account_move_reverse.py
- account_cancel_with_reversal/wizard/account_move_reverse_view.xml
- hr_expense_advance_clearing/models/hr_expense.py
- hr_expense_advance_clearing/views/hr_expense_view.xml
- hr_expense_auto_invoice/__openerp__.py
- hr_expense_auto_invoice/models/account_invoice.py
- hr_expense_auto_invoice/models/hr_expense.py
- hr_expense_auto_invoice/views/invoice_view.xml
- hr_expense_auto_invoice/workflow/hr_expense_workflow.xml
Hi Kitti,
/issues/653
/issues/654
/issues/655
/issues/656
Thanks,
Mustufa
> Enh fix expense advance clearing

- res_partner_ext/partner.py
- res_partner_ext/partner_view.xml
Please merge this to master krub.
> [FIX] name_get method for category

- hr_expense_advance_clearing/views/account_invoice_view.xml
- hr_expense_value_date/__init__.py
- hr_expense_value_date/__openerp__.py
- hr_expense_value_date/models/__init__.py
- hr_expense_value_date/models/account_voucher.py
- hr_expense_value_date/models/hr_expense.py
- hr_expense_value_date/security/ir.model.access.csv
- hr_expense_value_date/views/hr_expense_view.xml
- hr_expense_value_date/wizard/__init__.py
- hr_expense_value_date/wizard/change_value_date_wizard.py
- hr_expense_value_date/wizard/change_value_date_wizard_view.xml
Hi Kitti,
Ref: /issues/717
Thanks,
Mustufa
> [ADD]hr_expense_value_date: added new module for issues/717

- account_invoice_status_history/models/account_invoice.py
- document_status_history/models/document_history.py
- hr_expense_status_history/data/hr_expense_history_rule.xml
- hr_expense_status_history/models/hr_expense.py
Hi Kitti,
Fix for https://github.com/pabi2/pb2_generic/pull/73 
Thanks,
> [FIX]status hisroty: fix for issue: issues/694

- account_budget_activity/models/account.py
- account_budget_activity/models/account_budget.py
- account_budget_activity/models/hr_expense.py
- account_budget_activity/views/account_view.xml
Hi Kitti,
Ref: /issues/624
Done for expense only for now, please check and if it is ok we will do it for other documents.
Regards,
Mustufa Rangwala
> [ENH]account_budget_activity: Added budget control for expense

- account_voucher_netpay/__init__.py
- account_voucher_netpay/__openerp__.py
- account_voucher_netpay/models/__init__.py
- account_voucher_netpay/models/account_voucher.py
- account_voucher_netpay/models/account_voucher_oldapi.py
- account_voucher_netpay/views/account_voucher_view.xml
Hi Kitti,
Ref: /issues/855
New module account_voucher_netpay migrated from customer_supplier_voucher v7. 
Todo: Convert to new API. 
Hook available here: https://github.com/pabi2/pb2_base_technical/pull/14
Thanks,
Mustufa
> [ADD]account_voucher_netpay: added new module ref: issues/855

- multi_lang_search/models/__init__.py
- multi_lang_search/models/object.py
Hi Kitti,
Ref: /issues/934
Fixed such way on any object you can search using some other fields as well. 
Thanks,
Mustufa
> [IMP]multi_lang_search: improved to search multiple fields.

- account_budget_activity/models/product.py
- l10n_th_fields/__init__.py
- l10n_th_fields/__openerp__.py
- l10n_th_fields/account.py
- l10n_th_fields/account_bank.py
- l10n_th_fields/account_bank_view.xml
- payment_export/__openerp__.py
- payment_export/models/__init__.py
- payment_export/models/account_voucher.py
- payment_export/models/cheque_lot.py
- payment_export/models/payment_export.py
- payment_export/models/payment_export_config.py
- payment_export/views/cheque_lot_view.xml
- payment_export/views/payment_export_config_view.xml
- payment_export/views/payment_export_view.xml
- payment_export/wizard/__init__.py
- payment_export/wizard/export_parser.py
- payment_export/wizard/export_parser_view.xml
- payment_export_text/__init__.py
- payment_export_text/__openerp__.py
- payment_export_text/models/__init__.py
- payment_export_text/models/export_payment.py
- payment_export_text/wizard/__init__.py
- payment_export_text/wizard/export_parser.py
Hi Kitti,
Ref: /issues/938
We have created two modules by giving your Proof of concept, please check and give your feedback if this model work or not... We have tried to create framework that can be used in future... Please do not go in much detail because we are going to improve it..:) 
Thanks,
Mustufa
> Enh payment export

- multi_lang_search/models/object.py
Hi Kitti,
Ref: /issues/934 Note: 12-13
Thanks,
Mustufa
> FIX: Sorting issue + partner open form, issue number 934

- l10n_th_vat_report/report/vat_report.py
- l10n_th_vat_report/views/report_view.xml
> [IMP]l10n_th_vat_report: fix for tax type all header not display

- l10n_th_account_tax_detail/models/account_tax_detail.py
- l10n_th_vat_report/__openerp__.py
- l10n_th_vat_report/report/vat_report.py
- l10n_th_vat_report/views/report_view.xml
- l10n_th_vat_report/wizard/__init__.py
- l10n_th_vat_report/wizard/output_wiz.py
- l10n_th_vat_report/wizard/output_xls.xml
- l10n_th_vat_report/wizard/vat_report_wizard.py
- l10n_th_vat_report/wizard/vat_report_wizard_view.xml
Hi Kitti,
Ref: issues/396#note-23
Thanks,
Mustufa
> Fix l10n th vat report

- account_bank_receipt_cancel_reason/__init__.py
- account_bank_receipt_cancel_reason/__openerp__.py
- account_bank_receipt_cancel_reason/model/__init__.py
- account_bank_receipt_cancel_reason/model/account_bank_receipt.py
- account_bank_receipt_cancel_reason/view/account_bank_receipt_view.xml
- account_bank_receipt_cancel_reason/wizard/__init__.py
- account_bank_receipt_cancel_reason/wizard/cancel_reason.py
- account_bank_receipt_cancel_reason/wizard/cancel_reason_view.xml
> new module account_bank_receipt_cancel_reason

- account_bank_receipt_cancel_reason/model/account_bank_receipt.py
- account_bank_receipt_cancel_reason/wizard/cancel_reason.py
p'nuii review for python coding standard in bank receipt cancel reason
> [IMP] Edit python coding standard

- payment_export/report/report.xml
P' nuii Please review for comment report in qweb
> [IMP] comment report for qweb

- hr_expense_advance_clearing/models/hr_expense.py
- hr_expense_advance_clearing/views/hr_expense_view.xml
P' nuii please review for Advance Clearing tab
> [IMP] add field validate_user_id

- multi_lang_search/models/object.py
- res_partner_ext/views/partner_view.xml
Hi Kitti,
Ref: 934 
Please check commit of res_partner_ext/views/partner_view.xml and then merge.
Regards,
Mustufa
> Fix multi lang search

- l10n_th_account_pnd_form/__init__.py
- l10n_th_account_pnd_form/controllers/__init__.py
- l10n_th_account_pnd_form/controllers/web_main.py
- l10n_th_account_pnd_form/report/report_pnd3_form_xls.jrxml
- l10n_th_account_pnd_form/wizard/print_pnd_form_wizard.py
> Enh l10n th pnd form to export in txt jakkrich.cha

- l10n_th_tax_report/report/account_tax_report.jrxml
- l10n_th_tax_report/wizard/tax_report_wizard.py
- l10n_th_tax_report/wizard/tax_report_wizard.xml
- ส่วนของหน้าจอครับ
- ส่วน jasper จังหวะโยนค่าไปผมใช้เป็นแบบ '1,2,3,4,5' ไปใส่ sql เหมือนจะยังไม่ได้ครับ
> [fix] ability to select report in Period Range

- account_budget_activity/models/account.py
- account_budget_activity/models/account_budget.py
- account_budget_activity/views/account_budget_view.xml
- account_budget_activity/views/account_view.xml
- account_budget_activity/wizard/budget_release_wizard.py
- account_budget_activity/wizard/budget_release_wizard_view.xml
Hi Kitti,
**Ref: issues/1365**
Regards,
Mustufa Rangwala
> Enh account budget activity new budget release

- multi_lang_search/models/object.py
Hi Kitti,
Ref: 1351
Regards,
Mustufa R
> [FIX]multi_lang_search: fix for 1-1 of 1 problem ref: issues/1351

- hr_expense_auto_invoice/models/hr_expense.py
- l10n_th_account/models/account_voucher.py
Hi Kitti,
Ref:issue/1362
Regards,
Mustufa
> Performance improve pb2 generic

- account_model_purchase_invoice_plan/__init__.py
- account_model_purchase_invoice_plan/__openerp__.py
- account_model_purchase_invoice_plan/models/__init__.py
- account_model_purchase_invoice_plan/models/account.py
- account_model_purchase_invoice_plan/views/account_view.xml
- account_subscription_enhanced/data/account_data.xml
> Kittiu add account model purchase invoice plan

- account_subscription_enhanced/models/account.py
- account_subscription_enhanced/views/account_view.xml
Hi Kitti,
Ref: issues/1419
Regards,
Mustufa R
> Enh account subscription enhanced

- base_translation_auto_create/__init__.py
- base_translation_auto_create/__openerp__.py
- base_translation_auto_create/models/__init__.py
- base_translation_auto_create/models/create.py
Hi Kitti,
Ref: /issues/1437
Regards,
Mustufa R
> [ADD]base_translation_auto_create: issues/1437
